{{- if .Values.apiIngress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: velero-api
    layer: api
    tier: backend
  {{- include "seriohub-velero.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 }}
{{- end }}
