apiVersion: v1
kind: Service
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-ui
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.type }}
  selector:
    layer: webserver
  {{- include "seriohub-velero.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ui.ports | toYaml | nindent 2 }}