apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-sa
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.apiSa.serviceAccount.annotations | nindent 4 }}